namespace DownloadsStack.Localization;

internal static partial class Catalog
{
    public static readonly Dictionary<string, string> Pl = new()
    {
        ["Tray_Tooltip"] = "Ostatnie pliki · Downloads Stack",
        ["Tray_Open"] = "Otwórz listę · Downloads Stack",
        ["Tray_Close"] = "Zamknij listę · Downloads Stack",
        ["Menu_Settings"] = "Ustawienia",
        ["Menu_Exit"] = "Zakończ",
        ["Settings_Title"] = "Ustawienia — Downloads Stack",
        ["Settings_Heading"] = "Twoje foldery",
        ["Settings_ListName"] = "Podłączone foldery",
        ["Settings_AddFolder"] = "+ Dodaj folder",
        ["Settings_Remove"] = "Usuń",
        ["Settings_Retry"] = "Ponów",
        ["Settings_Done"] = "Gotowe",
        ["Settings_AddDownloads"] = "+ Pobrane",
        ["Settings_PickFolder"] = "Dodaj folder",
        ["Settings_SaveFailed"] = "Zmiana nie została zapisana: {0}",
        ["Settings_Hardware"] = "Sprzętowa akceleracja grafiki",
        ["Settings_HardwareHint"] = "Płynniejsze animacje kosztem znacznie większego zużycia pamięci. Zastosowane po ponownym uruchomieniu.",
        ["Settings_Backdrop"] = "Krycie podkładu nazw",
        ["Settings_BackdropHint"] = "Ciemny podkład pod nazwą każdego pliku. Przy 0% nazwy pozostają bez niego.",
        ["Settings_Count"] = "Plików na liście",
        ["Settings_CountHint"] = "Ile najnowszych plików pokazuje panel. Na niskim ekranie zmieści się mniej.",
        ["Settings_Appearance"] = "Wygląd",
        ["Settings_Sort"] = "Sortowanie",
        ["Settings_SortReverse"] = "Odwrotna kolejność",
        ["Settings_SortHint"] = "„Data dodania” to moment pojawienia się pliku w folderze; pozostałe daty pochodzą z samego pliku.",
        ["Settings_Startup"] = "Uruchamianie",
        ["Settings_RunAtLogon"] = "Uruchamiaj razem z Windows",
        ["Settings_RunAtLogonHint"] = "Ikona pojawia się w zasobniku zaraz po zalogowaniu. Ten sam przełącznik jest w Menedżerze zadań, w sekcji „Aplikacje startowe”.",
        ["Settings_RunAtLogonBlocked"] = "Windows wyłączył to w sekcji „Aplikacje startowe” Menedżera zadań. Włączyć z powrotem można tylko tam.",
        ["Sort_DateAdded"] = "Data dodania",
        ["Sort_Name"] = "Nazwa",
        ["Sort_Type"] = "Typ",
        ["Sort_DateModified"] = "Data modyfikacji",
        ["Sort_DateCreated"] = "Data utworzenia",
        ["Sort_DateAccessed"] = "Data dostępu",
        ["List_Name"] = "Ostatnie pliki",
        ["Empty_NoSources"] = "Dodaj folder w ustawieniach",
        ["Empty_Reading"] = "Odczytywanie folderów…",
        ["Empty_AllUnavailable"] = "Wybrane foldery są niedostępne",
        ["Empty_NoFiles"] = "W wybranych folderach nie ma jeszcze plików",
        ["Unavailable_Count"] = "Niedostępne foldery: {0}",
        ["Source_Downloads"] = "Pobrane (folder systemowy)",
        ["Source_Ready"] = "Dostępny",
        ["Source_Probing"] = "Sprawdzanie folderu…",
        ["Source_Denied"] = "Brak dostępu do folderu",
        ["Source_Unavailable"] = "Folder niedostępny: {0}",
        ["Error_Settings"] = "Nie udało się odczytać ani zapisać ustawień: {0}",
        ["Error_SettingsShape"] = "Nieprawidłowa struktura ustawień.",
        ["Error_SettingsCorrupt"] = "Ustawienia są uszkodzone. Kopia zapasowa: {0}. Przywrócono ustawienia domyślne.",
        ["Error_SettingsRead"] = "Nie udało się odczytać ustawień: {0}. Używane są ustawienia domyślne, a plik pozostał bez zmian.",
        ["Error_Shortcut"] = "Nie udało się utworzyć skrótu: {0}",
        ["Error_IndexShape"] = "Nieprawidłowy indeks.",
        ["Error_IndexEntry"] = "Nieprawidłowy wpis indeksu.",
        ["Error_IndexCorrupt"] = "Indeks dat jest uszkodzony i zostanie utworzony ponownie. Twoje pliki nie zostały zmienione.",
        ["Error_IndexRead"] = "Nie udało się odczytać indeksu dat. Listę odtworzono na podstawie dat utworzenia plików: {0}",
        ["Error_IndexSave"] = "Nie udało się zapisać indeksu dat: {0}",
        ["Error_IndexFlush"] = "Indeks nie został zapisany przed zakończeniem procesu.",
        ["Error_FileMissing"] = "Plik już nie istnieje.",
        ["Error_DownloadsMissing"] = "Nie udało się znaleźć folderu „Pobrane”.",
        ["Error_WindowMissing"] = "Okno listy jest niedostępne.",
        ["Shortcut_Description"] = "Wspólna lista ostatnich plików z wybranych folderów",
    };
}
