namespace DownloadsStack.Localization;

internal static partial class Catalog
{
    public static readonly Dictionary<string, string> Hi = new()
    {
        ["Tray_Tooltip"] = "हाल की फ़ाइलें · Downloads Stack",
        ["Tray_Open"] = "सूची खोलें · Downloads Stack",
        ["Tray_Close"] = "सूची बंद करें · Downloads Stack",
        ["Menu_Settings"] = "सेटिंग्स",
        ["Menu_Exit"] = "बाहर निकलें",
        ["Settings_Title"] = "सेटिंग्स — Downloads Stack",
        ["Settings_Heading"] = "आपके फ़ोल्डर",
        ["Settings_ListName"] = "जुड़े हुए फ़ोल्डर",
        ["Settings_AddFolder"] = "+ फ़ोल्डर जोड़ें",
        ["Settings_Remove"] = "हटाएँ",
        ["Settings_Retry"] = "फिर से कोशिश करें",
        ["Settings_Done"] = "हो गया",
        ["Settings_AddDownloads"] = "+ डाउनलोड",
        ["Settings_PickFolder"] = "फ़ोल्डर जोड़ें",
        ["Settings_SaveFailed"] = "बदलाव सहेजा नहीं गया: {0}",
        ["Settings_Hardware"] = "हार्डवेयर ग्राफ़िक्स त्वरण",
        ["Settings_HardwareHint"] = "एनिमेशन अधिक सहज होते हैं, पर ऐप कहीं अधिक मेमोरी रखता है। पुनः आरंभ करने पर लागू होता है।",
        ["Settings_Backdrop"] = "नाम की पृष्ठभूमि की अपारदर्शिता",
        ["Settings_BackdropHint"] = "हर फ़ाइल नाम के नीचे गहरी पट्टी। 0% पर नाम बिना पट्टी के रहते हैं।",
        ["Settings_Count"] = "सूची में फ़ाइलें",
        ["Settings_CountHint"] = "पैनल कितनी नवीनतम फ़ाइलें दिखाता है। कम ऊँची स्क्रीन पर इससे कम ही समाती हैं।",
        ["Settings_Appearance"] = "दिखावट",
        ["Settings_Sort"] = "क्रमबद्ध करें",
        ["Settings_SortReverse"] = "उल्टा क्रम",
        ["Settings_SortHint"] = "“जोड़ने की तारीख” वह समय है जब फ़ाइल फ़ोल्डर में आई; बाकी तारीखें फ़ाइल से ही ली जाती हैं।",
        ["Settings_Startup"] = "स्टार्टअप",
        ["Settings_RunAtLogon"] = "Windows के साथ शुरू करें",
        ["Settings_RunAtLogonHint"] = "साइन इन करते ही आइकन ट्रे में आ जाता है। यही स्विच टास्क मैनेजर के “स्टार्टअप ऐप्स” में भी है।",
        ["Settings_RunAtLogonBlocked"] = "Windows ने इसे टास्क मैनेजर के “स्टार्टअप ऐप्स” में बंद कर दिया है। वापस चालू वहीं से किया जा सकता है।",
        ["Sort_DateAdded"] = "जोड़ने की तारीख",
        ["Sort_Name"] = "नाम",
        ["Sort_Type"] = "प्रकार",
        ["Sort_DateModified"] = "बदलने की तारीख",
        ["Sort_DateCreated"] = "बनाने की तारीख",
        ["Sort_DateAccessed"] = "खोलने की तारीख",
        ["List_Name"] = "हाल की फ़ाइलें",
        ["Empty_NoSources"] = "सेटिंग्स में एक फ़ोल्डर जोड़ें",
        ["Empty_Reading"] = "फ़ोल्डर पढ़े जा रहे हैं…",
        ["Empty_AllUnavailable"] = "चुने गए फ़ोल्डर उपलब्ध नहीं हैं",
        ["Empty_NoFiles"] = "चुने गए फ़ोल्डरों में अभी कोई फ़ाइल नहीं है",
        ["Unavailable_Count"] = "अनुपलब्ध फ़ोल्डर: {0}",
        ["Source_Downloads"] = "डाउनलोड (सिस्टम फ़ोल्डर)",
        ["Source_Ready"] = "उपलब्ध",
        ["Source_Probing"] = "फ़ोल्डर जाँचा जा रहा है…",
        ["Source_Denied"] = "फ़ोल्डर तक पहुँच नहीं है",
        ["Source_Unavailable"] = "फ़ोल्डर अनुपलब्ध: {0}",
        ["Error_Settings"] = "सेटिंग्स पढ़ी या सहेजी नहीं जा सकीं: {0}",
        ["Error_SettingsShape"] = "सेटिंग्स की संरचना अमान्य है।",
        ["Error_SettingsCorrupt"] = "सेटिंग्स क्षतिग्रस्त हैं। बैकअप: {0}। डिफ़ॉल्ट सेटिंग्स बहाल कर दी गई हैं।",
        ["Error_SettingsRead"] = "सेटिंग्स पढ़ी नहीं जा सकीं: {0}। डिफ़ॉल्ट सेटिंग्स का उपयोग हो रहा है और आपकी फ़ाइल अपरिवर्तित है।",
        ["Error_Shortcut"] = "शॉर्टकट नहीं बनाया जा सका: {0}",
        ["Error_IndexShape"] = "अमान्य अनुक्रमणिका।",
        ["Error_IndexEntry"] = "अमान्य अनुक्रमणिका प्रविष्टि।",
        ["Error_IndexCorrupt"] = "तिथि अनुक्रमणिका क्षतिग्रस्त है और दोबारा बनाई जाएगी। आपकी फ़ाइलें नहीं बदली गईं।",
        ["Error_IndexRead"] = "तिथि अनुक्रमणिका पढ़ी नहीं जा सकी। सूची फ़ाइलों की निर्माण तिथियों से बहाल की गई: {0}",
        ["Error_IndexSave"] = "तिथि अनुक्रमणिका सहेजी नहीं जा सकी: {0}",
        ["Error_IndexFlush"] = "प्रक्रिया समाप्त होने से पहले अनुक्रमणिका सहेजी नहीं गई।",
        ["Error_FileMissing"] = "यह फ़ाइल अब मौजूद नहीं है।",
        ["Error_DownloadsMissing"] = "“डाउनलोड” फ़ोल्डर नहीं मिल सका।",
        ["Error_WindowMissing"] = "सूची विंडो उपलब्ध नहीं है।",
        ["Shortcut_Description"] = "आपके चुने हुए फ़ोल्डरों की हाल की फ़ाइलों की एक साझा सूची",
    };
}
