namespace DownloadsStack.Localization;

internal static partial class Catalog
{
    public static readonly Dictionary<string, string> Ru = new()
    {
        ["Tray_Tooltip"] = "Последние файлы · Downloads Stack",
        ["Tray_Open"] = "Открыть список · Downloads Stack",
        ["Tray_Close"] = "Закрыть список · Downloads Stack",
        ["Menu_Settings"] = "Настройки",
        ["Menu_Exit"] = "Выход",
        ["Settings_Title"] = "Настройки — Downloads Stack",
        ["Settings_Heading"] = "Ваши папки",
        ["Settings_ListName"] = "Подключённые папки",
        ["Settings_AddFolder"] = "+ Добавить папку",
        ["Settings_Remove"] = "Убрать",
        ["Settings_Retry"] = "Повторить",
        ["Settings_Done"] = "Готово",
        ["Settings_AddDownloads"] = "+ Загрузки",
        ["Settings_PickFolder"] = "Добавить папку",
        ["Settings_SaveFailed"] = "Изменение не сохранено: {0}",
        ["List_Name"] = "Последние файлы",
        ["Empty_NoSources"] = "Добавьте папку в настройках",
        ["Empty_Reading"] = "Чтение папок…",
        ["Empty_AllUnavailable"] = "Выбранные папки недоступны",
        ["Empty_NoFiles"] = "В выбранных папках пока нет файлов",
        ["Unavailable_Count"] = "Недоступно папок: {0}",
        ["Source_Downloads"] = "Загрузки (системная папка)",
        ["Source_Ready"] = "Доступна",
        ["Source_Probing"] = "Проверка папки…",
        ["Source_Denied"] = "Нет доступа к папке",
        ["Source_Unavailable"] = "Папка недоступна: {0}",
        ["Error_Settings"] = "Не удалось прочитать или сохранить настройки: {0}",
        ["Error_SettingsShape"] = "Неверная структура настроек.",
        ["Error_SettingsCorrupt"] = "Настройки повреждены. Резервная копия: {0}. Восстановлены настройки по умолчанию.",
        ["Error_SettingsRead"] = "Не удалось прочитать настройки: {0}. Используются настройки по умолчанию, ваш файл не изменён.",
        ["Error_Shortcut"] = "Не удалось создать ярлык: {0}",
        ["Error_IndexShape"] = "Неверный индекс.",
        ["Error_IndexEntry"] = "Неверная запись индекса.",
        ["Error_IndexCorrupt"] = "Индекс дат повреждён и будет пересоздан. Пользовательские файлы не изменены.",
        ["Error_IndexRead"] = "Не удалось прочитать индекс дат. Список восстановлен по датам создания файлов: {0}",
        ["Error_IndexSave"] = "Не удалось сохранить индекс дат: {0}",
        ["Error_IndexFlush"] = "Индекс не сохранён до завершения процесса.",
        ["Error_FileMissing"] = "Файл больше не существует.",
        ["Error_DownloadsMissing"] = "Не удалось найти папку «Загрузки».",
        ["Error_WindowMissing"] = "Окно списка недоступно.",
        ["Shortcut_Description"] = "Общий список последних файлов выбранных папок",
    };
}
