namespace DownloadsStack.Localization;

internal static partial class Catalog
{
    public static readonly Dictionary<string, string> Ko = new()
    {
        ["Tray_Tooltip"] = "최근 파일 · Downloads Stack",
        ["Tray_Open"] = "목록 열기 · Downloads Stack",
        ["Tray_Close"] = "목록 닫기 · Downloads Stack",
        ["Menu_Settings"] = "설정",
        ["Menu_Exit"] = "종료",
        ["Settings_Title"] = "설정 — Downloads Stack",
        ["Settings_Heading"] = "내 폴더",
        ["Settings_ListName"] = "연결된 폴더",
        ["Settings_AddFolder"] = "+ 폴더 추가",
        ["Settings_Remove"] = "제거",
        ["Settings_Retry"] = "다시 시도",
        ["Settings_Done"] = "완료",
        ["Settings_AddDownloads"] = "+ 다운로드",
        ["Settings_PickFolder"] = "폴더 추가",
        ["Settings_SaveFailed"] = "변경 사항이 저장되지 않았습니다: {0}",
        ["Settings_Hardware"] = "하드웨어 그래픽 가속",
        ["Settings_HardwareHint"] = "애니메이션이 부드러워지지만 앱이 훨씬 많은 메모리를 사용합니다. 다시 시작한 후 적용됩니다.",
        ["Settings_Backdrop"] = "이름 배경 불투명도",
        ["Settings_BackdropHint"] = "각 파일 이름 아래의 어두운 배경. 0%이면 배경이 사라집니다.",
        ["Settings_Count"] = "목록에 표시할 파일 수",
        ["Settings_CountHint"] = "패널이 보여 주는 최신 파일의 수. 화면이 낮으면 이보다 적게 들어갑니다.",
        ["Settings_Appearance"] = "모양",
        ["Settings_Sort"] = "정렬 기준",
        ["Settings_SortReverse"] = "역순",
        ["Settings_SortHint"] = "‘추가한 날짜’는 파일이 폴더에 나타난 시점이며, 나머지 날짜는 파일 자체에서 읽습니다.",
        ["Settings_Startup"] = "시작",
        ["Settings_RunAtLogon"] = "Windows와 함께 시작",
        ["Settings_RunAtLogonHint"] = "로그인 직후 알림 영역에 아이콘이 나타납니다. 같은 스위치가 작업 관리자의 ‘시작 앱’에도 있습니다.",
        ["Settings_RunAtLogonBlocked"] = "작업 관리자의 ‘시작 앱’에서 Windows가 이 항목을 껐습니다. 다시 켜는 것은 그곳에서만 가능합니다.",
        ["Sort_DateAdded"] = "추가한 날짜",
        ["Sort_Name"] = "이름",
        ["Sort_Type"] = "유형",
        ["Sort_DateModified"] = "수정한 날짜",
        ["Sort_DateCreated"] = "만든 날짜",
        ["Sort_DateAccessed"] = "액세스한 날짜",
        ["List_Name"] = "최근 파일",
        ["Empty_NoSources"] = "설정에서 폴더를 추가하세요",
        ["Empty_Reading"] = "폴더를 읽는 중…",
        ["Empty_AllUnavailable"] = "선택한 폴더를 사용할 수 없습니다",
        ["Empty_NoFiles"] = "선택한 폴더에 아직 파일이 없습니다",
        ["Unavailable_Count"] = "사용할 수 없는 폴더: {0}",
        ["Source_Downloads"] = "다운로드 (시스템 폴더)",
        ["Source_Ready"] = "사용 가능",
        ["Source_Probing"] = "폴더를 확인하는 중…",
        ["Source_Denied"] = "폴더에 접근할 수 없습니다",
        ["Source_Unavailable"] = "폴더를 사용할 수 없습니다: {0}",
        ["Error_Settings"] = "설정을 읽거나 저장할 수 없습니다: {0}",
        ["Error_SettingsShape"] = "설정 구조가 올바르지 않습니다.",
        ["Error_SettingsCorrupt"] = "설정이 손상되었습니다. 백업: {0}. 기본 설정을 복원했습니다.",
        ["Error_SettingsRead"] = "설정을 읽을 수 없습니다: {0}. 기본 설정을 사용하며 파일은 변경하지 않았습니다.",
        ["Error_Shortcut"] = "바로 가기를 만들 수 없습니다: {0}",
        ["Error_IndexShape"] = "인덱스가 올바르지 않습니다.",
        ["Error_IndexEntry"] = "인덱스 항목이 올바르지 않습니다.",
        ["Error_IndexCorrupt"] = "날짜 인덱스가 손상되어 다시 만듭니다. 사용자 파일은 변경되지 않았습니다.",
        ["Error_IndexRead"] = "날짜 인덱스를 읽을 수 없습니다. 파일 생성 날짜를 기준으로 목록을 복원했습니다: {0}",
        ["Error_IndexSave"] = "날짜 인덱스를 저장할 수 없습니다: {0}",
        ["Error_IndexFlush"] = "프로세스가 종료되기 전에 인덱스를 저장하지 못했습니다.",
        ["Error_FileMissing"] = "파일이 더 이상 존재하지 않습니다.",
        ["Error_DownloadsMissing"] = "‘다운로드’ 폴더를 찾을 수 없습니다.",
        ["Error_WindowMissing"] = "목록 창을 사용할 수 없습니다.",
        ["Shortcut_Description"] = "선택한 폴더의 최근 파일을 모아 보여 주는 목록",
    };
}
