namespace DownloadsStack.Localization;

internal static partial class Catalog
{
    public static readonly Dictionary<string, string> Pt = new()
    {
        ["Tray_Tooltip"] = "Arquivos recentes · Downloads Stack",
        ["Tray_Open"] = "Abrir a lista · Downloads Stack",
        ["Tray_Close"] = "Fechar a lista · Downloads Stack",
        ["Menu_Settings"] = "Configurações",
        ["Menu_Exit"] = "Sair",
        ["Settings_Title"] = "Configurações — Downloads Stack",
        ["Settings_Heading"] = "Suas pastas",
        ["Settings_ListName"] = "Pastas conectadas",
        ["Settings_AddFolder"] = "+ Adicionar pasta",
        ["Settings_Remove"] = "Remover",
        ["Settings_Retry"] = "Tentar novamente",
        ["Settings_Done"] = "Concluído",
        ["Settings_AddDownloads"] = "+ Downloads",
        ["Settings_PickFolder"] = "Adicionar pasta",
        ["Settings_SaveFailed"] = "A alteração não foi salva: {0}",
        ["Settings_Hardware"] = "Aceleração gráfica por hardware",
        ["Settings_HardwareHint"] = "Animações mais suaves, ao custo de o aplicativo reter muito mais memória. Aplicado após reiniciar.",
        ["Settings_Backdrop"] = "Opacidade do fundo dos nomes",
        ["Settings_BackdropHint"] = "A placa escura sob o nome de cada arquivo. Em 0% os nomes ficam sem ela.",
        ["Settings_Count"] = "Arquivos na lista",
        ["Settings_CountHint"] = "Quantos dos arquivos mais recentes o painel mostra. Em uma tela baixa cabem menos.",
        ["Settings_Appearance"] = "Aparência",
        ["Settings_Sort"] = "Ordenar por",
        ["Settings_SortReverse"] = "Ordem inversa",
        ["Settings_SortHint"] = "“Data de adição” é quando o arquivo apareceu na pasta; as demais datas vêm do próprio arquivo.",
        ["Settings_Startup"] = "Inicialização",
        ["Settings_RunAtLogon"] = "Iniciar com o Windows",
        ["Settings_RunAtLogonHint"] = "O ícone aparece na área de notificação logo após você entrar. A mesma opção está no Gerenciador de Tarefas, em “Aplicativos de inicialização”.",
        ["Settings_RunAtLogonBlocked"] = "O Windows desativou isto em “Aplicativos de inicialização” do Gerenciador de Tarefas. Só é possível reativar por lá.",
        ["Sort_DateAdded"] = "Data de adição",
        ["Sort_Name"] = "Nome",
        ["Sort_Type"] = "Tipo",
        ["Sort_DateModified"] = "Data de modificação",
        ["Sort_DateCreated"] = "Data de criação",
        ["Sort_DateAccessed"] = "Data de acesso",
        ["List_Name"] = "Arquivos recentes",
        ["Empty_NoSources"] = "Adicione uma pasta nas configurações",
        ["Empty_Reading"] = "Lendo as pastas…",
        ["Empty_AllUnavailable"] = "As pastas selecionadas estão indisponíveis",
        ["Empty_NoFiles"] = "Ainda não há arquivos nas pastas selecionadas",
        ["Unavailable_Count"] = "Pastas indisponíveis: {0}",
        ["Source_Downloads"] = "Downloads (pasta do sistema)",
        ["Source_Ready"] = "Disponível",
        ["Source_Probing"] = "Verificando a pasta…",
        ["Source_Denied"] = "Sem acesso à pasta",
        ["Source_Unavailable"] = "Pasta indisponível: {0}",
        ["Error_Settings"] = "Não foi possível ler ou salvar as configurações: {0}",
        ["Error_SettingsShape"] = "Estrutura de configurações inválida.",
        ["Error_SettingsCorrupt"] = "As configurações estão corrompidas. Backup: {0}. As configurações padrão foram restauradas.",
        ["Error_SettingsRead"] = "Não foi possível ler as configurações: {0}. As configurações padrão estão em uso e seu arquivo não foi alterado.",
        ["Error_Shortcut"] = "Não foi possível criar o atalho: {0}",
        ["Error_IndexShape"] = "Índice inválido.",
        ["Error_IndexEntry"] = "Entrada de índice inválida.",
        ["Error_IndexCorrupt"] = "O índice de datas está corrompido e será recriado. Seus arquivos não foram alterados.",
        ["Error_IndexRead"] = "Não foi possível ler o índice de datas. A lista foi restaurada pelas datas de criação dos arquivos: {0}",
        ["Error_IndexSave"] = "Não foi possível salvar o índice de datas: {0}",
        ["Error_IndexFlush"] = "O índice não foi salvo antes do encerramento do processo.",
        ["Error_FileMissing"] = "O arquivo não existe mais.",
        ["Error_DownloadsMissing"] = "Não foi possível encontrar a pasta “Downloads”.",
        ["Error_WindowMissing"] = "A janela da lista está indisponível.",
        ["Shortcut_Description"] = "Uma lista única dos arquivos recentes das pastas que você escolher",
    };
}
