namespace DownloadsStack.Localization;

internal static partial class Catalog
{
    public static readonly Dictionary<string, string> Ko = new()
    {
        ["Tray_Tooltip"] = "최근 파일 · Downloads Stack",
        ["Tray_Open"] = "목록 열기 · Downloads Stack",
        ["Tray_Close"] = "목록 닫기 · Downloads Stack",
        ["Menu_Settings"] = "설정",
        ["Menu_Exit"] = "종료",
        ["Settings_Title"] = "설정 — Downloads Stack",
        ["Settings_Heading"] = "내 폴더",
        ["Settings_ListName"] = "연결된 폴더",
        ["Settings_AddFolder"] = "+ 폴더 추가",
        ["Settings_Remove"] = "제거",
        ["Settings_Retry"] = "다시 시도",
        ["Settings_Done"] = "완료",
        ["Settings_AddDownloads"] = "+ 다운로드",
        ["Settings_PickFolder"] = "폴더 추가",
        ["Settings_SaveFailed"] = "변경 사항이 저장되지 않았습니다: {0}",
        ["List_Name"] = "최근 파일",
        ["Empty_NoSources"] = "설정에서 폴더를 추가하세요",
        ["Empty_Reading"] = "폴더를 읽는 중…",
        ["Empty_AllUnavailable"] = "선택한 폴더를 사용할 수 없습니다",
        ["Empty_NoFiles"] = "선택한 폴더에 아직 파일이 없습니다",
        ["Unavailable_Count"] = "사용할 수 없는 폴더: {0}",
        ["Source_Downloads"] = "다운로드 (시스템 폴더)",
        ["Source_Ready"] = "사용 가능",
        ["Source_Probing"] = "폴더를 확인하는 중…",
        ["Source_Denied"] = "폴더에 접근할 수 없습니다",
        ["Source_Unavailable"] = "폴더를 사용할 수 없습니다: {0}",
        ["Error_Settings"] = "설정을 읽거나 저장할 수 없습니다: {0}",
        ["Error_SettingsShape"] = "설정 구조가 올바르지 않습니다.",
        ["Error_SettingsCorrupt"] = "설정이 손상되었습니다. 백업: {0}. 기본 설정을 복원했습니다.",
        ["Error_SettingsRead"] = "설정을 읽을 수 없습니다: {0}. 기본 설정을 사용하며 파일은 변경하지 않았습니다.",
        ["Error_Shortcut"] = "바로 가기를 만들 수 없습니다: {0}",
        ["Error_IndexShape"] = "인덱스가 올바르지 않습니다.",
        ["Error_IndexEntry"] = "인덱스 항목이 올바르지 않습니다.",
        ["Error_IndexCorrupt"] = "날짜 인덱스가 손상되어 다시 만듭니다. 사용자 파일은 변경되지 않았습니다.",
        ["Error_IndexRead"] = "날짜 인덱스를 읽을 수 없습니다. 파일 생성 날짜를 기준으로 목록을 복원했습니다: {0}",
        ["Error_IndexSave"] = "날짜 인덱스를 저장할 수 없습니다: {0}",
        ["Error_IndexFlush"] = "프로세스가 종료되기 전에 인덱스를 저장하지 못했습니다.",
        ["Error_FileMissing"] = "파일이 더 이상 존재하지 않습니다.",
        ["Error_DownloadsMissing"] = "‘다운로드’ 폴더를 찾을 수 없습니다.",
        ["Error_WindowMissing"] = "목록 창을 사용할 수 없습니다.",
        ["Shortcut_Description"] = "선택한 폴더의 최근 파일을 모아 보여 주는 목록",
    };
}
