namespace DownloadsStack.Localization;

internal static partial class Catalog
{
    public static readonly Dictionary<string, string> Ja = new()
    {
        ["Tray_Tooltip"] = "最近のファイル · Downloads Stack",
        ["Tray_Open"] = "リストを開く · Downloads Stack",
        ["Tray_Close"] = "リストを閉じる · Downloads Stack",
        ["Menu_Settings"] = "設定",
        ["Menu_Exit"] = "終了",
        ["Settings_Title"] = "設定 — Downloads Stack",
        ["Settings_Heading"] = "フォルダー",
        ["Settings_ListName"] = "接続済みのフォルダー",
        ["Settings_AddFolder"] = "+ フォルダーを追加",
        ["Settings_Remove"] = "削除",
        ["Settings_Retry"] = "再試行",
        ["Settings_Done"] = "完了",
        ["Settings_AddDownloads"] = "+ ダウンロード",
        ["Settings_PickFolder"] = "フォルダーを追加",
        ["Settings_SaveFailed"] = "変更は保存されませんでした: {0}",
        ["List_Name"] = "最近のファイル",
        ["Empty_NoSources"] = "設定でフォルダーを追加してください",
        ["Empty_Reading"] = "フォルダーを読み込んでいます…",
        ["Empty_AllUnavailable"] = "選択したフォルダーは利用できません",
        ["Empty_NoFiles"] = "選択したフォルダーにはまだファイルがありません",
        ["Unavailable_Count"] = "利用できないフォルダー: {0}",
        ["Source_Downloads"] = "ダウンロード (システム フォルダー)",
        ["Source_Ready"] = "利用可能",
        ["Source_Probing"] = "フォルダーを確認しています…",
        ["Source_Denied"] = "フォルダーにアクセスできません",
        ["Source_Unavailable"] = "フォルダーを利用できません: {0}",
        ["Error_Settings"] = "設定を読み込みまたは保存できませんでした: {0}",
        ["Error_SettingsShape"] = "設定の構造が正しくありません。",
        ["Error_SettingsCorrupt"] = "設定が破損しています。バックアップ: {0}。既定の設定を復元しました。",
        ["Error_SettingsRead"] = "設定を読み込めませんでした: {0}。既定の設定を使用します。ファイルは変更していません。",
        ["Error_Shortcut"] = "ショートカットを作成できませんでした: {0}",
        ["Error_IndexShape"] = "インデックスが正しくありません。",
        ["Error_IndexEntry"] = "インデックスの項目が正しくありません。",
        ["Error_IndexCorrupt"] = "日付インデックスが破損しているため再作成します。ファイルは変更されていません。",
        ["Error_IndexRead"] = "日付インデックスを読み込めませんでした。ファイルの作成日時からリストを復元しました: {0}",
        ["Error_IndexSave"] = "日付インデックスを保存できませんでした: {0}",
        ["Error_IndexFlush"] = "プロセス終了前にインデックスを保存できませんでした。",
        ["Error_FileMissing"] = "このファイルはもう存在しません。",
        ["Error_DownloadsMissing"] = "「ダウンロード」フォルダーが見つかりませんでした。",
        ["Error_WindowMissing"] = "リストのウィンドウを利用できません。",
        ["Shortcut_Description"] = "選択したフォルダーの最近のファイルをまとめたリスト",
    };
}
