namespace DownloadsStack.Localization;

internal static partial class Catalog
{
    public static readonly Dictionary<string, string> Hi = new()
    {
        ["Tray_Tooltip"] = "हाल की फ़ाइलें · Downloads Stack",
        ["Tray_Open"] = "सूची खोलें · Downloads Stack",
        ["Tray_Close"] = "सूची बंद करें · Downloads Stack",
        ["Menu_Settings"] = "सेटिंग्स",
        ["Menu_Exit"] = "बाहर निकलें",
        ["Settings_Title"] = "सेटिंग्स — Downloads Stack",
        ["Settings_Heading"] = "आपके फ़ोल्डर",
        ["Settings_ListName"] = "जुड़े हुए फ़ोल्डर",
        ["Settings_AddFolder"] = "+ फ़ोल्डर जोड़ें",
        ["Settings_Remove"] = "हटाएँ",
        ["Settings_Retry"] = "फिर से कोशिश करें",
        ["Settings_Done"] = "हो गया",
        ["Settings_AddDownloads"] = "+ डाउनलोड",
        ["Settings_PickFolder"] = "फ़ोल्डर जोड़ें",
        ["Settings_SaveFailed"] = "बदलाव सहेजा नहीं गया: {0}",
        ["List_Name"] = "हाल की फ़ाइलें",
        ["Empty_NoSources"] = "सेटिंग्स में एक फ़ोल्डर जोड़ें",
        ["Empty_Reading"] = "फ़ोल्डर पढ़े जा रहे हैं…",
        ["Empty_AllUnavailable"] = "चुने गए फ़ोल्डर उपलब्ध नहीं हैं",
        ["Empty_NoFiles"] = "चुने गए फ़ोल्डरों में अभी कोई फ़ाइल नहीं है",
        ["Unavailable_Count"] = "अनुपलब्ध फ़ोल्डर: {0}",
        ["Source_Downloads"] = "डाउनलोड (सिस्टम फ़ोल्डर)",
        ["Source_Ready"] = "उपलब्ध",
        ["Source_Probing"] = "फ़ोल्डर जाँचा जा रहा है…",
        ["Source_Denied"] = "फ़ोल्डर तक पहुँच नहीं है",
        ["Source_Unavailable"] = "फ़ोल्डर अनुपलब्ध: {0}",
        ["Error_Settings"] = "सेटिंग्स पढ़ी या सहेजी नहीं जा सकीं: {0}",
        ["Error_SettingsShape"] = "सेटिंग्स की संरचना अमान्य है।",
        ["Error_SettingsCorrupt"] = "सेटिंग्स क्षतिग्रस्त हैं। बैकअप: {0}। डिफ़ॉल्ट सेटिंग्स बहाल कर दी गई हैं।",
        ["Error_SettingsRead"] = "सेटिंग्स पढ़ी नहीं जा सकीं: {0}। डिफ़ॉल्ट सेटिंग्स का उपयोग हो रहा है और आपकी फ़ाइल अपरिवर्तित है।",
        ["Error_Shortcut"] = "शॉर्टकट नहीं बनाया जा सका: {0}",
        ["Error_IndexShape"] = "अमान्य अनुक्रमणिका।",
        ["Error_IndexEntry"] = "अमान्य अनुक्रमणिका प्रविष्टि।",
        ["Error_IndexCorrupt"] = "तिथि अनुक्रमणिका क्षतिग्रस्त है और दोबारा बनाई जाएगी। आपकी फ़ाइलें नहीं बदली गईं।",
        ["Error_IndexRead"] = "तिथि अनुक्रमणिका पढ़ी नहीं जा सकी। सूची फ़ाइलों की निर्माण तिथियों से बहाल की गई: {0}",
        ["Error_IndexSave"] = "तिथि अनुक्रमणिका सहेजी नहीं जा सकी: {0}",
        ["Error_IndexFlush"] = "प्रक्रिया समाप्त होने से पहले अनुक्रमणिका सहेजी नहीं गई।",
        ["Error_FileMissing"] = "यह फ़ाइल अब मौजूद नहीं है।",
        ["Error_DownloadsMissing"] = "“डाउनलोड” फ़ोल्डर नहीं मिल सका।",
        ["Error_WindowMissing"] = "सूची विंडो उपलब्ध नहीं है।",
        ["Shortcut_Description"] = "आपके चुने हुए फ़ोल्डरों की हाल की फ़ाइलों की एक साझा सूची",
    };
}
