namespace DownloadsStack.Localization;

internal static partial class Catalog
{
    public static readonly Dictionary<string, string> It = new()
    {
        ["Tray_Tooltip"] = "File recenti · Downloads Stack",
        ["Tray_Open"] = "Apri l’elenco · Downloads Stack",
        ["Tray_Close"] = "Chiudi l’elenco · Downloads Stack",
        ["Menu_Settings"] = "Impostazioni",
        ["Menu_Exit"] = "Esci",
        ["Settings_Title"] = "Impostazioni — Downloads Stack",
        ["Settings_Heading"] = "Le tue cartelle",
        ["Settings_ListName"] = "Cartelle collegate",
        ["Settings_AddFolder"] = "+ Aggiungi cartella",
        ["Settings_Remove"] = "Rimuovi",
        ["Settings_Retry"] = "Riprova",
        ["Settings_Done"] = "Fatto",
        ["Settings_AddDownloads"] = "+ Download",
        ["Settings_PickFolder"] = "Aggiungi cartella",
        ["Settings_SaveFailed"] = "Modifica non salvata: {0}",
        ["List_Name"] = "File recenti",
        ["Empty_NoSources"] = "Aggiungi una cartella nelle impostazioni",
        ["Empty_Reading"] = "Lettura delle cartelle…",
        ["Empty_AllUnavailable"] = "Le cartelle selezionate non sono disponibili",
        ["Empty_NoFiles"] = "Ancora nessun file nelle cartelle selezionate",
        ["Unavailable_Count"] = "Cartelle non disponibili: {0}",
        ["Source_Downloads"] = "Download (cartella di sistema)",
        ["Source_Ready"] = "Disponibile",
        ["Source_Probing"] = "Verifica della cartella…",
        ["Source_Denied"] = "Nessun accesso alla cartella",
        ["Source_Unavailable"] = "Cartella non disponibile: {0}",
        ["Error_Settings"] = "Impossibile leggere o salvare le impostazioni: {0}",
        ["Error_SettingsShape"] = "Struttura delle impostazioni non valida.",
        ["Error_SettingsCorrupt"] = "Le impostazioni sono danneggiate. Backup: {0}. Sono state ripristinate le impostazioni predefinite.",
        ["Error_SettingsRead"] = "Impossibile leggere le impostazioni: {0}. Sono in uso le impostazioni predefinite e il file non è stato modificato.",
        ["Error_Shortcut"] = "Impossibile creare il collegamento: {0}",
        ["Error_IndexShape"] = "Indice non valido.",
        ["Error_IndexEntry"] = "Voce di indice non valida.",
        ["Error_IndexCorrupt"] = "L’indice delle date è danneggiato e verrà ricreato. I tuoi file non sono stati modificati.",
        ["Error_IndexRead"] = "Impossibile leggere l’indice delle date. L’elenco è stato ripristinato dalle date di creazione dei file: {0}",
        ["Error_IndexSave"] = "Impossibile salvare l’indice delle date: {0}",
        ["Error_IndexFlush"] = "L’indice non è stato salvato prima della chiusura del processo.",
        ["Error_FileMissing"] = "Il file non esiste più.",
        ["Error_DownloadsMissing"] = "Impossibile trovare la cartella «Download».",
        ["Error_WindowMissing"] = "La finestra dell’elenco non è disponibile.",
        ["Shortcut_Description"] = "Un unico elenco dei file recenti delle cartelle che scegli",
    };
}
