namespace DownloadsStack.Localization;

internal static partial class Catalog
{
    public static readonly Dictionary<string, string> Es = new()
    {
        ["Tray_Tooltip"] = "Archivos recientes · Downloads Stack",
        ["Tray_Open"] = "Abrir la lista · Downloads Stack",
        ["Tray_Close"] = "Cerrar la lista · Downloads Stack",
        ["Menu_Settings"] = "Configuración",
        ["Menu_Exit"] = "Salir",
        ["Settings_Title"] = "Configuración — Downloads Stack",
        ["Settings_Heading"] = "Tus carpetas",
        ["Settings_ListName"] = "Carpetas conectadas",
        ["Settings_AddFolder"] = "+ Añadir carpeta",
        ["Settings_Remove"] = "Quitar",
        ["Settings_Retry"] = "Reintentar",
        ["Settings_Done"] = "Listo",
        ["Settings_AddDownloads"] = "+ Descargas",
        ["Settings_PickFolder"] = "Añadir carpeta",
        ["Settings_SaveFailed"] = "El cambio no se guardó: {0}",
        ["List_Name"] = "Archivos recientes",
        ["Empty_NoSources"] = "Añade una carpeta en la configuración",
        ["Empty_Reading"] = "Leyendo carpetas…",
        ["Empty_AllUnavailable"] = "Las carpetas seleccionadas no están disponibles",
        ["Empty_NoFiles"] = "Aún no hay archivos en las carpetas seleccionadas",
        ["Unavailable_Count"] = "Carpetas no disponibles: {0}",
        ["Source_Downloads"] = "Descargas (carpeta del sistema)",
        ["Source_Ready"] = "Disponible",
        ["Source_Probing"] = "Comprobando la carpeta…",
        ["Source_Denied"] = "Sin acceso a la carpeta",
        ["Source_Unavailable"] = "Carpeta no disponible: {0}",
        ["Error_Settings"] = "No se pudo leer ni guardar la configuración: {0}",
        ["Error_SettingsShape"] = "Estructura de configuración no válida.",
        ["Error_SettingsCorrupt"] = "La configuración está dañada. Copia de seguridad: {0}. Se restauró la configuración predeterminada.",
        ["Error_SettingsRead"] = "No se pudo leer la configuración: {0}. Se usa la configuración predeterminada y su archivo no se modificó.",
        ["Error_Shortcut"] = "No se pudo crear el acceso directo: {0}",
        ["Error_IndexShape"] = "Índice no válido.",
        ["Error_IndexEntry"] = "Entrada de índice no válida.",
        ["Error_IndexCorrupt"] = "El índice de fechas está dañado y se creará de nuevo. Tus archivos no se modificaron.",
        ["Error_IndexRead"] = "No se pudo leer el índice de fechas. La lista se restauró con las fechas de creación de los archivos: {0}",
        ["Error_IndexSave"] = "No se pudo guardar el índice de fechas: {0}",
        ["Error_IndexFlush"] = "El índice no se guardó antes de cerrar el proceso.",
        ["Error_FileMissing"] = "El archivo ya no existe.",
        ["Error_DownloadsMissing"] = "No se pudo encontrar la carpeta «Descargas».",
        ["Error_WindowMissing"] = "La ventana de la lista no está disponible.",
        ["Shortcut_Description"] = "Una sola lista con los archivos recientes de las carpetas que elijas",
    };
}
