namespace DownloadsStack.Localization;

internal static partial class Catalog
{
    public static readonly Dictionary<string, string> Zh = new()
    {
        ["Tray_Tooltip"] = "最近的文件 · Downloads Stack",
        ["Tray_Open"] = "打开列表 · Downloads Stack",
        ["Tray_Close"] = "关闭列表 · Downloads Stack",
        ["Menu_Settings"] = "设置",
        ["Menu_Exit"] = "退出",
        ["Settings_Title"] = "设置 — Downloads Stack",
        ["Settings_Heading"] = "你的文件夹",
        ["Settings_ListName"] = "已连接的文件夹",
        ["Settings_AddFolder"] = "+ 添加文件夹",
        ["Settings_Remove"] = "移除",
        ["Settings_Retry"] = "重试",
        ["Settings_Done"] = "完成",
        ["Settings_AddDownloads"] = "+ 下载",
        ["Settings_PickFolder"] = "添加文件夹",
        ["Settings_SaveFailed"] = "更改未保存：{0}",
        ["Settings_Hardware"] = "硬件图形加速",
        ["Settings_HardwareHint"] = "动画更流畅，代价是应用占用的内存明显增加。重启后生效。",
        ["Settings_Backdrop"] = "文件名衬底不透明度",
        ["Settings_BackdropHint"] = "每个文件名下方的深色衬底。为 0% 时名称不再有衬底。",
        ["Settings_Count"] = "列表中的文件数",
        ["Settings_CountHint"] = "面板显示多少个最新文件。屏幕高度不足时会显示得更少。",
        ["Settings_Appearance"] = "外观",
        ["Settings_Sort"] = "排序方式",
        ["Settings_SortReverse"] = "反向排序",
        ["Settings_SortHint"] = "“添加日期”是文件出现在文件夹中的时间；其余日期取自文件本身。",
        ["Settings_Startup"] = "启动",
        ["Settings_RunAtLogon"] = "随 Windows 一起启动",
        ["Settings_RunAtLogonHint"] = "登录后托盘中立即出现图标。任务管理器的“启动应用”里也有同一个开关。",
        ["Settings_RunAtLogonBlocked"] = "Windows 已在任务管理器的“启动应用”中关闭了它，只能在那里重新开启。",
        ["Sort_DateAdded"] = "添加日期",
        ["Sort_Name"] = "名称",
        ["Sort_Type"] = "类型",
        ["Sort_DateModified"] = "修改日期",
        ["Sort_DateCreated"] = "创建日期",
        ["Sort_DateAccessed"] = "访问日期",
        ["List_Name"] = "最近的文件",
        ["Empty_NoSources"] = "请在设置中添加文件夹",
        ["Empty_Reading"] = "正在读取文件夹…",
        ["Empty_AllUnavailable"] = "所选文件夹不可用",
        ["Empty_NoFiles"] = "所选文件夹中暂时没有文件",
        ["Unavailable_Count"] = "不可用的文件夹：{0}",
        ["Source_Downloads"] = "下载（系统文件夹）",
        ["Source_Ready"] = "可用",
        ["Source_Probing"] = "正在检查文件夹…",
        ["Source_Denied"] = "无权访问该文件夹",
        ["Source_Unavailable"] = "文件夹不可用：{0}",
        ["Error_Settings"] = "无法读取或保存设置：{0}",
        ["Error_SettingsShape"] = "设置结构无效。",
        ["Error_SettingsCorrupt"] = "设置已损坏。备份：{0}。已恢复默认设置。",
        ["Error_SettingsRead"] = "无法读取设置：{0}。当前使用默认设置，您的文件未被修改。",
        ["Error_Shortcut"] = "无法创建快捷方式：{0}",
        ["Error_IndexShape"] = "索引无效。",
        ["Error_IndexEntry"] = "索引条目无效。",
        ["Error_IndexCorrupt"] = "日期索引已损坏，将重新创建。你的文件未被修改。",
        ["Error_IndexRead"] = "无法读取日期索引。列表已根据文件创建日期恢复：{0}",
        ["Error_IndexSave"] = "无法保存日期索引：{0}",
        ["Error_IndexFlush"] = "进程结束前未能保存索引。",
        ["Error_FileMissing"] = "该文件已不存在。",
        ["Error_DownloadsMissing"] = "找不到“下载”文件夹。",
        ["Error_WindowMissing"] = "列表窗口不可用。",
        ["Shortcut_Description"] = "所选文件夹中最新文件的统一列表",
    };
}
