namespace DownloadsStack.Localization;

internal static partial class Catalog
{
    public static readonly Dictionary<string, string> Tr = new()
    {
        ["Tray_Tooltip"] = "Son dosyalar · Downloads Stack",
        ["Tray_Open"] = "Listeyi aç · Downloads Stack",
        ["Tray_Close"] = "Listeyi kapat · Downloads Stack",
        ["Menu_Settings"] = "Ayarlar",
        ["Menu_Exit"] = "Çıkış",
        ["Settings_Title"] = "Ayarlar — Downloads Stack",
        ["Settings_Heading"] = "Klasörleriniz",
        ["Settings_ListName"] = "Bağlı klasörler",
        ["Settings_AddFolder"] = "+ Klasör ekle",
        ["Settings_Remove"] = "Kaldır",
        ["Settings_Retry"] = "Yeniden dene",
        ["Settings_Done"] = "Tamam",
        ["Settings_AddDownloads"] = "+ İndirilenler",
        ["Settings_PickFolder"] = "Klasör ekle",
        ["Settings_SaveFailed"] = "Değişiklik kaydedilmedi: {0}",
        ["Settings_Hardware"] = "Donanım grafik hızlandırma",
        ["Settings_HardwareHint"] = "Animasyonlar daha akıcı olur, karşılığında uygulama çok daha fazla bellek tutar. Yeniden başlatıldığında uygulanır.",
        ["Settings_Backdrop"] = "Ad zemininin opaklığı",
        ["Settings_BackdropHint"] = "Her dosya adının altındaki koyu zemin. %0 olduğunda adlar zeminsiz kalır.",
        ["Settings_Count"] = "Listedeki dosya sayısı",
        ["Settings_CountHint"] = "Panelin en yeni dosyalardan kaçını gösterdiği. Kısa bir ekrana daha azı sığar.",
        ["Settings_Appearance"] = "Görünüm",
        ["Settings_Sort"] = "Sıralama",
        ["Settings_SortReverse"] = "Ters sıra",
        ["Settings_SortHint"] = "“Eklenme tarihi”, dosyanın klasörde göründüğü andır; diğer tarihler dosyanın kendisinden okunur.",
        ["Settings_Startup"] = "Başlangıç",
        ["Settings_RunAtLogon"] = "Windows ile birlikte başlat",
        ["Settings_RunAtLogonHint"] = "Simge, oturum açtıktan hemen sonra bildirim alanında görünür. Aynı anahtar Görev Yöneticisi’ndeki “Başlangıç uygulamaları” bölümünde de var.",
        ["Settings_RunAtLogonBlocked"] = "Windows bunu Görev Yöneticisi’ndeki “Başlangıç uygulamaları” bölümünde kapattı. Yeniden açmak yalnızca oradan mümkün.",
        ["Sort_DateAdded"] = "Eklenme tarihi",
        ["Sort_Name"] = "Ad",
        ["Sort_Type"] = "Tür",
        ["Sort_DateModified"] = "Değiştirilme tarihi",
        ["Sort_DateCreated"] = "Oluşturulma tarihi",
        ["Sort_DateAccessed"] = "Erişim tarihi",
        ["List_Name"] = "Son dosyalar",
        ["Empty_NoSources"] = "Ayarlardan bir klasör ekleyin",
        ["Empty_Reading"] = "Klasörler okunuyor…",
        ["Empty_AllUnavailable"] = "Seçilen klasörler kullanılamıyor",
        ["Empty_NoFiles"] = "Seçilen klasörlerde henüz dosya yok",
        ["Unavailable_Count"] = "Kullanılamayan klasörler: {0}",
        ["Source_Downloads"] = "İndirilenler (sistem klasörü)",
        ["Source_Ready"] = "Kullanılabilir",
        ["Source_Probing"] = "Klasör denetleniyor…",
        ["Source_Denied"] = "Klasöre erişim yok",
        ["Source_Unavailable"] = "Klasör kullanılamıyor: {0}",
        ["Error_Settings"] = "Ayarlar okunamadı veya kaydedilemedi: {0}",
        ["Error_SettingsShape"] = "Geçersiz ayar yapısı.",
        ["Error_SettingsCorrupt"] = "Ayarlar bozuk. Yedek: {0}. Varsayılan ayarlar geri yüklendi.",
        ["Error_SettingsRead"] = "Ayarlar okunamadı: {0}. Varsayılan ayarlar kullanılıyor ve dosyanız değiştirilmedi.",
        ["Error_Shortcut"] = "Kısayol oluşturulamadı: {0}",
        ["Error_IndexShape"] = "Geçersiz dizin.",
        ["Error_IndexEntry"] = "Geçersiz dizin kaydı.",
        ["Error_IndexCorrupt"] = "Tarih dizini bozuk ve yeniden oluşturulacak. Dosyalarınız değiştirilmedi.",
        ["Error_IndexRead"] = "Tarih dizini okunamadı. Liste, dosyaların oluşturulma tarihlerine göre geri yüklendi: {0}",
        ["Error_IndexSave"] = "Tarih dizini kaydedilemedi: {0}",
        ["Error_IndexFlush"] = "Dizin, işlem sona ermeden önce kaydedilmedi.",
        ["Error_FileMissing"] = "Dosya artık mevcut değil.",
        ["Error_DownloadsMissing"] = "“İndirilenler” klasörü bulunamadı.",
        ["Error_WindowMissing"] = "Liste penceresi kullanılamıyor.",
        ["Shortcut_Description"] = "Seçtiğiniz klasörlerdeki son dosyaların tek listesi",
    };
}
