namespace DownloadsStack.Localization;

internal static partial class Catalog
{
    public static readonly Dictionary<string, string> De = new()
    {
        ["Tray_Tooltip"] = "Zuletzt verwendete Dateien · Downloads Stack",
        ["Tray_Open"] = "Liste öffnen · Downloads Stack",
        ["Tray_Close"] = "Liste schließen · Downloads Stack",
        ["Menu_Settings"] = "Einstellungen",
        ["Menu_Exit"] = "Beenden",
        ["Settings_Title"] = "Einstellungen — Downloads Stack",
        ["Settings_Heading"] = "Ihre Ordner",
        ["Settings_ListName"] = "Verbundene Ordner",
        ["Settings_AddFolder"] = "+ Ordner hinzufügen",
        ["Settings_Remove"] = "Entfernen",
        ["Settings_Retry"] = "Wiederholen",
        ["Settings_Done"] = "Fertig",
        ["Settings_AddDownloads"] = "+ Downloads",
        ["Settings_PickFolder"] = "Ordner hinzufügen",
        ["Settings_SaveFailed"] = "Änderung nicht gespeichert: {0}",
        ["List_Name"] = "Zuletzt verwendete Dateien",
        ["Empty_NoSources"] = "Fügen Sie in den Einstellungen einen Ordner hinzu",
        ["Empty_Reading"] = "Ordner werden gelesen…",
        ["Empty_AllUnavailable"] = "Die ausgewählten Ordner sind nicht verfügbar",
        ["Empty_NoFiles"] = "Noch keine Dateien in den ausgewählten Ordnern",
        ["Unavailable_Count"] = "Nicht verfügbare Ordner: {0}",
        ["Source_Downloads"] = "Downloads (Systemordner)",
        ["Source_Ready"] = "Verfügbar",
        ["Source_Probing"] = "Ordner wird geprüft…",
        ["Source_Denied"] = "Kein Zugriff auf den Ordner",
        ["Source_Unavailable"] = "Ordner nicht verfügbar: {0}",
        ["Error_Settings"] = "Die Einstellungen konnten nicht gelesen oder gespeichert werden: {0}",
        ["Error_SettingsShape"] = "Ungültige Struktur der Einstellungen.",
        ["Error_SettingsCorrupt"] = "Die Einstellungen sind beschädigt. Sicherung: {0}. Die Standardeinstellungen wurden wiederhergestellt.",
        ["Error_SettingsRead"] = "Die Einstellungen konnten nicht gelesen werden: {0}. Es gelten die Standardeinstellungen; Ihre Datei wurde nicht verändert.",
        ["Error_Shortcut"] = "Die Verknüpfung konnte nicht erstellt werden: {0}",
        ["Error_IndexShape"] = "Ungültiger Index.",
        ["Error_IndexEntry"] = "Ungültiger Indexeintrag.",
        ["Error_IndexCorrupt"] = "Der Datumsindex ist beschädigt und wird neu erstellt. Ihre Dateien wurden nicht verändert.",
        ["Error_IndexRead"] = "Der Datumsindex konnte nicht gelesen werden. Die Liste wurde anhand der Erstellungsdaten der Dateien wiederhergestellt: {0}",
        ["Error_IndexSave"] = "Der Datumsindex konnte nicht gespeichert werden: {0}",
        ["Error_IndexFlush"] = "Der Index wurde vor dem Beenden des Prozesses nicht gespeichert.",
        ["Error_FileMissing"] = "Die Datei existiert nicht mehr.",
        ["Error_DownloadsMissing"] = "Der Ordner „Downloads“ wurde nicht gefunden.",
        ["Error_WindowMissing"] = "Das Listenfenster ist nicht verfügbar.",
        ["Shortcut_Description"] = "Eine gemeinsame Liste der neuesten Dateien aus den von Ihnen gewählten Ordnern",
    };
}
