namespace DownloadsStack.Localization;

internal static partial class Catalog
{
    public static readonly Dictionary<string, string> Uk = new()
    {
        ["Tray_Tooltip"] = "Останні файли · Downloads Stack",
        ["Tray_Open"] = "Відкрити список · Downloads Stack",
        ["Tray_Close"] = "Закрити список · Downloads Stack",
        ["Menu_Settings"] = "Налаштування",
        ["Menu_Exit"] = "Вихід",
        ["Settings_Title"] = "Налаштування — Downloads Stack",
        ["Settings_Heading"] = "Ваші папки",
        ["Settings_ListName"] = "Підключені папки",
        ["Settings_AddFolder"] = "+ Додати папку",
        ["Settings_Remove"] = "Прибрати",
        ["Settings_Retry"] = "Повторити",
        ["Settings_Done"] = "Готово",
        ["Settings_AddDownloads"] = "+ Завантаження",
        ["Settings_PickFolder"] = "Додати папку",
        ["Settings_SaveFailed"] = "Зміну не збережено: {0}",
        ["Settings_Hardware"] = "Апаратне прискорення графіки",
        ["Settings_HardwareHint"] = "Анімації плавніші ціною помітно більших витрат пам'яті. Застосується після перезапуску.",
        ["Settings_Backdrop"] = "Непрозорість підкладки назв",
        ["Settings_BackdropHint"] = "Темна підкладка під іменем кожного файлу. За 0% назви лишаються без неї.",
        ["Settings_Count"] = "Файлів у списку",
        ["Settings_CountHint"] = "Скільки найновіших файлів показує панель. На невисокому екрані поміститься менше.",
        ["Settings_Appearance"] = "Оформлення",
        ["Settings_Sort"] = "Сортування",
        ["Settings_SortReverse"] = "Зворотний порядок",
        ["Settings_SortHint"] = "«Дата додавання» — коли файл з’явився в папці; інші дати беруться із самого файлу.",
        ["Settings_Startup"] = "Запуск",
        ["Settings_RunAtLogon"] = "Запускати разом із Windows",
        ["Settings_RunAtLogonHint"] = "Значок з’являється в треї одразу після входу в систему. Той самий перемикач є в диспетчері завдань, на вкладці «Автозавантаження».",
        ["Settings_RunAtLogonBlocked"] = "Windows вимкнув автозапуск на вкладці «Автозавантаження» диспетчера завдань. Увімкнути назад можна лише там.",
        ["Sort_DateAdded"] = "Дата додавання",
        ["Sort_Name"] = "Ім’я",
        ["Sort_Type"] = "Тип",
        ["Sort_DateModified"] = "Дата змінення",
        ["Sort_DateCreated"] = "Дата створення",
        ["Sort_DateAccessed"] = "Дата доступу",
        ["List_Name"] = "Останні файли",
        ["Empty_NoSources"] = "Додайте папку в налаштуваннях",
        ["Empty_Reading"] = "Читання папок…",
        ["Empty_AllUnavailable"] = "Вибрані папки недоступні",
        ["Empty_NoFiles"] = "У вибраних папках поки немає файлів",
        ["Unavailable_Count"] = "Недоступно папок: {0}",
        ["Source_Downloads"] = "Завантаження (системна папка)",
        ["Source_Ready"] = "Доступна",
        ["Source_Probing"] = "Перевірка папки…",
        ["Source_Denied"] = "Немає доступу до папки",
        ["Source_Unavailable"] = "Папка недоступна: {0}",
        ["Error_Settings"] = "Не вдалося прочитати або зберегти налаштування: {0}",
        ["Error_SettingsShape"] = "Неправильна структура налаштувань.",
        ["Error_SettingsCorrupt"] = "Налаштування пошкоджено. Резервна копія: {0}. Відновлено налаштування за умовчанням.",
        ["Error_SettingsRead"] = "Не вдалося прочитати налаштування: {0}. Використовуються налаштування за умовчанням, ваш файл не змінено.",
        ["Error_Shortcut"] = "Не вдалося створити ярлик: {0}",
        ["Error_IndexShape"] = "Неправильний індекс.",
        ["Error_IndexEntry"] = "Неправильний запис індексу.",
        ["Error_IndexCorrupt"] = "Індекс дат пошкоджено, його буде створено заново. Файли користувача не змінено.",
        ["Error_IndexRead"] = "Не вдалося прочитати індекс дат. Список відновлено за датами створення файлів: {0}",
        ["Error_IndexSave"] = "Не вдалося зберегти індекс дат: {0}",
        ["Error_IndexFlush"] = "Індекс не збережено до завершення процесу.",
        ["Error_FileMissing"] = "Файл більше не існує.",
        ["Error_DownloadsMissing"] = "Не вдалося знайти папку «Завантаження».",
        ["Error_WindowMissing"] = "Вікно списку недоступне.",
        ["Shortcut_Description"] = "Спільний список останніх файлів вибраних папок",
    };
}
