namespace DownloadsStack.Localization;

internal static partial class Catalog
{
    public static readonly Dictionary<string, string> Fr = new()
    {
        ["Tray_Tooltip"] = "Fichiers récents · Downloads Stack",
        ["Tray_Open"] = "Ouvrir la liste · Downloads Stack",
        ["Tray_Close"] = "Fermer la liste · Downloads Stack",
        ["Menu_Settings"] = "Paramètres",
        ["Menu_Exit"] = "Quitter",
        ["Settings_Title"] = "Paramètres — Downloads Stack",
        ["Settings_Heading"] = "Vos dossiers",
        ["Settings_ListName"] = "Dossiers connectés",
        ["Settings_AddFolder"] = "+ Ajouter un dossier",
        ["Settings_Remove"] = "Retirer",
        ["Settings_Retry"] = "Réessayer",
        ["Settings_Done"] = "Terminé",
        ["Settings_AddDownloads"] = "+ Téléchargements",
        ["Settings_PickFolder"] = "Ajouter un dossier",
        ["Settings_SaveFailed"] = "Modification non enregistrée : {0}",
        ["List_Name"] = "Fichiers récents",
        ["Empty_NoSources"] = "Ajoutez un dossier dans les paramètres",
        ["Empty_Reading"] = "Lecture des dossiers…",
        ["Empty_AllUnavailable"] = "Les dossiers sélectionnés sont indisponibles",
        ["Empty_NoFiles"] = "Aucun fichier pour l’instant dans les dossiers sélectionnés",
        ["Unavailable_Count"] = "Dossiers indisponibles : {0}",
        ["Source_Downloads"] = "Téléchargements (dossier système)",
        ["Source_Ready"] = "Disponible",
        ["Source_Probing"] = "Vérification du dossier…",
        ["Source_Denied"] = "Pas d’accès au dossier",
        ["Source_Unavailable"] = "Dossier indisponible : {0}",
        ["Error_Settings"] = "Impossible de lire ou d’enregistrer les paramètres : {0}",
        ["Error_SettingsShape"] = "Structure des paramètres non valide.",
        ["Error_SettingsCorrupt"] = "Les paramètres sont endommagés. Sauvegarde : {0}. Les paramètres par défaut ont été restaurés.",
        ["Error_SettingsRead"] = "Impossible de lire les paramètres : {0}. Les paramètres par défaut sont utilisés et votre fichier n’a pas été modifié.",
        ["Error_Shortcut"] = "Impossible de créer le raccourci : {0}",
        ["Error_IndexShape"] = "Index non valide.",
        ["Error_IndexEntry"] = "Entrée d’index non valide.",
        ["Error_IndexCorrupt"] = "L’index des dates est endommagé et sera reconstruit. Vos fichiers n’ont pas été modifiés.",
        ["Error_IndexRead"] = "Impossible de lire l’index des dates. La liste a été restaurée d’après les dates de création des fichiers : {0}",
        ["Error_IndexSave"] = "Impossible d’enregistrer l’index des dates : {0}",
        ["Error_IndexFlush"] = "L’index n’a pas été enregistré avant la fermeture du processus.",
        ["Error_FileMissing"] = "Le fichier n’existe plus.",
        ["Error_DownloadsMissing"] = "Impossible de trouver le dossier « Téléchargements ».",
        ["Error_WindowMissing"] = "La fenêtre de la liste est indisponible.",
        ["Shortcut_Description"] = "Une liste unique des fichiers récents des dossiers que vous choisissez",
    };
}
