namespace DownloadsStack.Localization;

internal static partial class Catalog
{
    public static readonly Dictionary<string, string> Ja = new()
    {
        ["Tray_Tooltip"] = "最近のファイル · Downloads Stack",
        ["Tray_Open"] = "リストを開く · Downloads Stack",
        ["Tray_Close"] = "リストを閉じる · Downloads Stack",
        ["Menu_Settings"] = "設定",
        ["Menu_Exit"] = "終了",
        ["Settings_Title"] = "設定 — Downloads Stack",
        ["Settings_Heading"] = "フォルダー",
        ["Settings_ListName"] = "接続済みのフォルダー",
        ["Settings_AddFolder"] = "+ フォルダーを追加",
        ["Settings_Remove"] = "削除",
        ["Settings_Retry"] = "再試行",
        ["Settings_Done"] = "完了",
        ["Settings_AddDownloads"] = "+ ダウンロード",
        ["Settings_PickFolder"] = "フォルダーを追加",
        ["Settings_SaveFailed"] = "変更は保存されませんでした: {0}",
        ["Settings_Hardware"] = "ハードウェア グラフィック アクセラレーション",
        ["Settings_HardwareHint"] = "アニメーションが滑らかになりますが、アプリのメモリ使用量が大幅に増えます。再起動後に適用されます。",
        ["Settings_Backdrop"] = "ファイル名の下地の不透明度",
        ["Settings_BackdropHint"] = "各ファイル名の下に敷く暗い下地。0% では下地がなくなります。",
        ["Settings_Count"] = "一覧に表示するファイル数",
        ["Settings_CountHint"] = "パネルが表示する新しいファイルの数。画面の高さが足りないときはこれより少なくなります。",
        ["Settings_Appearance"] = "外観",
        ["Settings_Sort"] = "並べ替え",
        ["Settings_SortReverse"] = "逆順",
        ["Settings_SortHint"] = "「追加日時」はファイルがフォルダーに現れた時点です。ほかの日時はファイル自体から読み取ります。",
        ["Settings_Startup"] = "スタートアップ",
        ["Settings_RunAtLogon"] = "Windows と一緒に起動する",
        ["Settings_RunAtLogonHint"] = "サインインの直後に通知領域へアイコンが現れます。同じ切り替えはタスク マネージャーの「スタートアップ アプリ」にもあります。",
        ["Settings_RunAtLogonBlocked"] = "タスク マネージャーの「スタートアップ アプリ」で Windows が無効にしました。元に戻せるのはそこだけです。",
        ["Sort_DateAdded"] = "追加日時",
        ["Sort_Name"] = "名前",
        ["Sort_Type"] = "種類",
        ["Sort_DateModified"] = "更新日時",
        ["Sort_DateCreated"] = "作成日時",
        ["Sort_DateAccessed"] = "アクセス日時",
        ["List_Name"] = "最近のファイル",
        ["Empty_NoSources"] = "設定でフォルダーを追加してください",
        ["Empty_Reading"] = "フォルダーを読み込んでいます…",
        ["Empty_AllUnavailable"] = "選択したフォルダーは利用できません",
        ["Empty_NoFiles"] = "選択したフォルダーにはまだファイルがありません",
        ["Unavailable_Count"] = "利用できないフォルダー: {0}",
        ["Source_Downloads"] = "ダウンロード (システム フォルダー)",
        ["Source_Ready"] = "利用可能",
        ["Source_Probing"] = "フォルダーを確認しています…",
        ["Source_Denied"] = "フォルダーにアクセスできません",
        ["Source_Unavailable"] = "フォルダーを利用できません: {0}",
        ["Error_Settings"] = "設定を読み込みまたは保存できませんでした: {0}",
        ["Error_SettingsShape"] = "設定の構造が正しくありません。",
        ["Error_SettingsCorrupt"] = "設定が破損しています。バックアップ: {0}。既定の設定を復元しました。",
        ["Error_SettingsRead"] = "設定を読み込めませんでした: {0}。既定の設定を使用します。ファイルは変更していません。",
        ["Error_Shortcut"] = "ショートカットを作成できませんでした: {0}",
        ["Error_IndexShape"] = "インデックスが正しくありません。",
        ["Error_IndexEntry"] = "インデックスの項目が正しくありません。",
        ["Error_IndexCorrupt"] = "日付インデックスが破損しているため再作成します。ファイルは変更されていません。",
        ["Error_IndexRead"] = "日付インデックスを読み込めませんでした。ファイルの作成日時からリストを復元しました: {0}",
        ["Error_IndexSave"] = "日付インデックスを保存できませんでした: {0}",
        ["Error_IndexFlush"] = "プロセス終了前にインデックスを保存できませんでした。",
        ["Error_FileMissing"] = "このファイルはもう存在しません。",
        ["Error_DownloadsMissing"] = "「ダウンロード」フォルダーが見つかりませんでした。",
        ["Error_WindowMissing"] = "リストのウィンドウを利用できません。",
        ["Shortcut_Description"] = "選択したフォルダーの最近のファイルをまとめたリスト",
    };
}
